name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Updated checkout action

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload artifact
      uses: actions/upload-artifact@v4  # Updated to v4
      if: github.event_name == 'push'  # Fixed the condition (old one was incorrect)
      with:
        name: apk-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 7  # Optional: Adjust artifact retention period
